import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('A');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('Admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await expect(page.getByRole('link', { name: 'Admin' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'PIM' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Leave' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Time' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Recruitment' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'My Info' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Performance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Dashboard' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Directory' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Maintenance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Claim' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Buzz' })).toBeVisible();
  await page.getByRole('link', { name: 'Admin' }).click();
  await expect(page.getByRole('link', { name: 'Admin' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'PIM' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Leave' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Time' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Recruitment' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'My Info' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Performance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Dashboard' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Directory' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Maintenance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Claim' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Buzz' })).toBeVisible();
  await page.getByRole('link', { name: 'PIM' }).click();
  await expect(page.getByRole('link', { name: 'Admin' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'PIM' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Leave' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Time' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Recruitment' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'My Info' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Performance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Dashboard' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Directory' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Maintenance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Claim' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Buzz' })).toBeVisible();
  await page.getByRole('link', { name: 'Leave' }).click();
  await expect(page.getByRole('link', { name: 'Admin' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'PIM' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Leave', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Time' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Recruitment' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'My Info' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Performance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Dashboard' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Directory' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Maintenance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Claim' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Claim' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Buzz' })).toBeVisible();
  await page.getByRole('link', { name: 'Time' }).click();
  await expect(page.getByRole('link', { name: 'Admin' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'PIM' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Leave' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Time' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Recruitment' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'My Info' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Performance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Dashboard' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Directory' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Maintenance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Claim' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Buzz' })).toBeVisible();
  await page.getByRole('link', { name: 'Recruitment' }).click();
  await expect(page.getByRole('link', { name: 'Admin' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'PIM' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Leave' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Time' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Recruitment' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'My Info' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Performance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Dashboard' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Dashboard' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Directory' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Maintenance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Claim' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Buzz' })).toBeVisible();
  await page.getByRole('link', { name: 'My Info' }).click();
  await expect(page.getByRole('link', { name: 'Admin' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'PIM' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Leave' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Time' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Recruitment' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'My Info' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Performance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Dashboard' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Directory' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Maintenance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Claim' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Buzz' })).toBeVisible();
  await page.getByRole('link', { name: 'Performance' }).click();
  await expect(page.getByRole('link', { name: 'Admin' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'PIM' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Leave' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Time' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Recruitment' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'My Info' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Performance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Dashboard' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Directory' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Maintenance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Claim' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Buzz' })).toBeVisible();
  await page.getByRole('link', { name: 'Directory' }).click();
  await expect(page.getByRole('link', { name: 'Admin' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'PIM' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Leave' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Time' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Recruitment' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'My Info' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Performance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Dashboard' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Directory' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Maintenance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Claim' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Buzz' })).toBeVisible();
});